const usersData = [
  { consumer_email: 'Samppa Nori', provider: 'Samppa Nori', role: 'Member', status: 'Success' },
  { consumer_email: 'Estavan Lykos', provider: 'Estavan Lykos', role: 'Staff', status: 'Canceled' },
  { consumer_email: 'Chetan Mohamed', provider: 'Chetan Mohamed', role: 'Admin', status: 'Received' },
  { consumer_email: 'Derick Maximinus', provider: 'Derick Maximinus', role: 'Member', status: 'Sending' },
  { consumer_email: 'Friderik Dávid', provider: 'Friderik Dávid', role: 'Staff', status: 'Success' },
  { consumer_email: 'Yiorgos Avraamu', provider: 'Yiorgos Avraamu', role: 'Member', status: 'Success' },
  { consumer_email: 'Avram Tarasios', provider: 'Avram Tarasios', role: 'Staff', status: 'Canceled', _classes: 'table-success' },
  { consumer_email: 'Quintin Ed', provider: 'Quintin Ed', role: 'Admin', status: 'Received' },
  { consumer_email: 'Enéas Kwadwo', provider: 'Enéas Kwadwo', role: 'Member', status: 'Sending' },
  { consumer_email: 'Agapetus Tadeáš', provider: 'Agapetus Tadeáš', role: 'Staff', status: 'Success' },
  { consumer_email: 'Carwyn Fachtna', provider: 'Carwyn Fachtna', role: 'Member', status: 'Success', _classes: 'table-success' },
  { consumer_email: 'Nehemiah Tatius', provider: 'Nehemiah Tatius', role: 'Staff', status: 'Canceled' },
  { consumer_email: 'Ebbe Gemariah', provider: 'Ebbe Gemariah', role: 'Admin', status: 'Received' },
  { consumer_email: 'Eustorgios Amulius', provider: 'Eustorgios Amulius', role: 'Member', status: 'Sending' },
  { consumer_email: 'Leopold Gáspár', provider: 'Leopold Gáspár', role: 'Staff', status: 'Success' },
  { consumer_email: 'Pompeius René', provider: 'Pompeius René', role: 'Member', status: 'Success' },
  { consumer_email: 'Paĉjo Jadon', provider: 'Paĉjo Jadon', role: 'Staff', status: 'Canceled' },
  { consumer_email: 'Micheal Mercurius', provider: 'Micheal Mercurius', role: 'Admin', status: 'Received' },
  { consumer_email: 'Ganesha Dubhghall', provider: 'Ganesha Dubhghall', role: 'Member', status: 'Sending' },
  { consumer_email: 'Hiroto Šimun', provider: 'Hiroto Šimun', role: 'Staff', status: 'Success' },
  { consumer_email: 'Vishnu Serghei', provider: 'Vishnu Serghei', role: 'Member', status: 'Success' },
  { consumer_email: 'Zbyněk Phoibos', provider: 'Zbyněk Phoibos', role: 'Staff', status: 'Canceled' },
  { consumer_email: 'Einar Randall', provider: 'Einar Randall', role: 'Admin', status: 'Received', _classes: 'table-danger' },
  { consumer_email: 'Félix Troels', provider: 'Félix Troels', role: 'Staff', status: 'Success' },
  { consumer_email: 'Aulus Agmundr', provider: 'Aulus Agmundr', role: 'Member', status: 'Sending' },
];

export default usersData;
