const usersData = [
  { username: 'Samppa Nori', provider: 'Samppa Nori', role: 'Member', status: 'Active' },
  { username: 'Estavan Lykos', provider: 'Estavan Lykos', role: 'Staff', status: 'Banned' },
  { username: 'Chetan Mohamed', provider: 'Chetan Mohamed', role: 'Admin', status: 'Inactive' },
  { username: 'Derick Maximinus', provider: 'Derick Maximinus', role: 'Member', status: 'Pending' },
  { username: 'Friderik Dávid', provider: 'Friderik Dávid', role: 'Staff', status: 'Active' },
  { username: 'Yiorgos Avraamu', provider: 'Yiorgos Avraamu', role: 'Member', status: 'Active' },
  { username: 'Avram Tarasios', provider: 'Avram Tarasios', role: 'Staff', status: 'Banned', _classes: 'table-success' },
  { username: 'Quintin Ed', provider: 'Quintin Ed', role: 'Admin', status: 'Inactive' },
  { username: 'Enéas Kwadwo', provider: 'Enéas Kwadwo', role: 'Member', status: 'Pending' },
  { username: 'Agapetus Tadeáš', provider: 'Agapetus Tadeáš', role: 'Staff', status: 'Active' },
  { username: 'Carwyn Fachtna', provider: 'Carwyn Fachtna', role: 'Member', status: 'Active', _classes: 'table-success' },
  { username: 'Nehemiah Tatius', provider: 'Nehemiah Tatius', role: 'Staff', status: 'Banned' },
  { username: 'Ebbe Gemariah', provider: 'Ebbe Gemariah', role: 'Admin', status: 'Inactive' },
  { username: 'Eustorgios Amulius', provider: 'Eustorgios Amulius', role: 'Member', status: 'Pending' },
  { username: 'Leopold Gáspár', provider: 'Leopold Gáspár', role: 'Staff', status: 'Active' },
  { username: 'Pompeius René', provider: 'Pompeius René', role: 'Member', status: 'Active' },
  { username: 'Paĉjo Jadon', provider: 'Paĉjo Jadon', role: 'Staff', status: 'Banned' },
  { username: 'Micheal Mercurius', provider: 'Micheal Mercurius', role: 'Admin', status: 'Inactive' },
  { username: 'Ganesha Dubhghall', provider: 'Ganesha Dubhghall', role: 'Member', status: 'Pending' },
  { username: 'Hiroto Šimun', provider: 'Hiroto Šimun', role: 'Staff', status: 'Active' },
  { username: 'Vishnu Serghei', provider: 'Vishnu Serghei', role: 'Member', status: 'Active' },
  { username: 'Zbyněk Phoibos', provider: 'Zbyněk Phoibos', role: 'Staff', status: 'Banned' },
  { username: 'Einar Randall', provider: 'Einar Randall', role: 'Admin', status: 'Inactive', _classes: 'table-danger' },
  { username: 'Félix Troels', provider: 'Félix Troels', role: 'Staff', status: 'Active' },
  { username: 'Aulus Agmundr', provider: 'Aulus Agmundr', role: 'Member', status: 'Pending' },
];

export default usersData;
